/**
 *
 * @author jotaele
 */
package GUI;

public class TiempoHoyPanel extends javax.swing.JPanel {

    /**
     * Creates new form TiempoHoyPanel
     */
    public TiempoHoyPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tiempo = new javax.swing.JLabel();
        Maxima = new javax.swing.JLabel();
        Temperatura = new javax.swing.JLabel();
        Minima = new javax.swing.JLabel();
        Humedad = new javax.swing.JLabel();
        Viento = new javax.swing.JLabel();
        Amanecer = new javax.swing.JLabel();
        Atardecer = new javax.swing.JLabel();
        Temperatura1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setLayout(null);

        Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/lluvia.png"))); // NOI18N
        Tiempo.setText("  ");
        Tiempo.setMaximumSize(new java.awt.Dimension(70, 70));
        Tiempo.setMinimumSize(new java.awt.Dimension(70, 70));
        Tiempo.setName(""); // NOI18N
        add(Tiempo);
        Tiempo.setBounds(30, 30, 70, 70);

        Maxima.setFont(new java.awt.Font("Ubuntu Light", 1, 28)); // NOI18N
        Maxima.setForeground(new java.awt.Color(255, 0, 0));
        Maxima.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Maxima.setText("90.0");
        add(Maxima);
        Maxima.setBounds(340, 70, 60, 30);

        Temperatura.setFont(new java.awt.Font("Ubuntu", 1, 41)); // NOI18N
        Temperatura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Temperatura.setText("90.0");
        add(Temperatura);
        Temperatura.setBounds(110, 30, 90, 40);

        Minima.setFont(new java.awt.Font("Ubuntu Light", 1, 28)); // NOI18N
        Minima.setForeground(new java.awt.Color(45, 75, 242));
        Minima.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Minima.setText("90.0");
        add(Minima);
        Minima.setBounds(340, 30, 60, 30);

        Humedad.setFont(new java.awt.Font("Ubuntu Light", 1, 15)); // NOI18N
        Humedad.setForeground(new java.awt.Color(87, 87, 87));
        Humedad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Humedad.setText("90");
        add(Humedad);
        Humedad.setBounds(180, 160, 30, 18);

        Viento.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Viento.setForeground(new java.awt.Color(87, 87, 87));
        Viento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Viento.setText("10.0");
        add(Viento);
        Viento.setBounds(60, 160, 40, 20);

        Amanecer.setFont(new java.awt.Font("Ubuntu Light", 1, 15)); // NOI18N
        Amanecer.setForeground(new java.awt.Color(87, 87, 87));
        Amanecer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Amanecer.setText("00:00");
        add(Amanecer);
        Amanecer.setBounds(300, 150, 60, 40);

        Atardecer.setFont(new java.awt.Font("Ubuntu Light", 1, 15)); // NOI18N
        Atardecer.setForeground(new java.awt.Color(87, 87, 87));
        Atardecer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Atardecer.setText("00:00");
        add(Atardecer);
        Atardecer.setBounds(410, 150, 60, 40);

        Temperatura1.setFont(new java.awt.Font("Ubuntu", 0, 41)); // NOI18N
        Temperatura1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Temperatura1.setText("ºC");
        add(Temperatura1);
        Temperatura1.setBounds(200, 30, 60, 40);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 6, 0));
        jLabel1.setText("ºC");
        add(jLabel1);
        jLabel1.setBounds(410, 70, 50, 30);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Máxima:");
        add(jLabel2);
        jLabel2.setBounds(280, 70, 50, 30);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 75, 242));
        jLabel3.setText("ºC");
        add(jLabel3);
        jLabel3.setBounds(410, 30, 40, 30);

        Descripcion.setFont(new java.awt.Font("Ubuntu Light", 2, 14)); // NOI18N
        Descripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Descripcion.setText("Descripción");
        add(Descripcion);
        Descripcion.setBounds(110, 80, 150, 20);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Mínima:");
        add(jLabel4);
        jLabel4.setBounds(280, 30, 50, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/puesta.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(370, 140, 27, 60);

        jLabel6.setForeground(new java.awt.Color(87, 87, 87));
        jLabel6.setText("%");
        add(jLabel6);
        jLabel6.setBounds(220, 160, 20, 18);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/viento.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(30, 160, 27, 20);

        jLabel8.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(87, 87, 87));
        jLabel8.setText("m/s");
        add(jLabel8);
        jLabel8.setBounds(110, 160, 30, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/humedad.png"))); // NOI18N
        add(jLabel9);
        jLabel9.setBounds(157, 150, 30, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/amanecer.png"))); // NOI18N
        add(jLabel10);
        jLabel10.setBounds(260, 140, 27, 60);

        jSeparator3.setBackground(new java.awt.Color(197, 197, 197));
        jSeparator3.setForeground(new java.awt.Color(211, 211, 211));
        add(jSeparator3);
        jSeparator3.setBounds(30, 130, 430, 10);
    }// </editor-fold>//GEN-END:initComponents

    public void setAmanecer(String a) {
        this.Amanecer.setText(a);
    }

    public void setAtardecer(String a) {
        this.Atardecer.setText(a);
    }

    public void setHumedad(String h) {
        this.Humedad.setText(h);
    }

    // Elegimos el icono correspondiente según lo que recibimos del servidor.
    public void setTiempo(String i) {
        
        switch(i) {
            case "01d": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/sol.png")));
                        Descripcion.setText("Despejado");
                        break;
            case "01n": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/luna.png")));
                        Descripcion.setText("Despejado");
                        break;
            case "02d": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nubesol.png")));
                        Descripcion.setText("Parcialmente Nublado");
                        break;
            case "02n": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nubeluna.png")));
                        Descripcion.setText("Parcialmente Nublado");
                        break;
            case "03d": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nubes.png")));
                        Descripcion.setText("Nublado");
                        break;
            case "03n": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nubes.png")));
                        Descripcion.setText("Nublado");
                        break;
            case "04d": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/cubierto.png")));
                        Descripcion.setText("Cubierto");
                        break;
            case "04n": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/cubierto.png")));
                        Descripcion.setText("Cubierto");
                        break;
            case "09d": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/lluvia.png")));
                        Descripcion.setText("Lluvia Intensa");
                        break;
            case "09n": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/lluvia.png")));
                        Descripcion.setText("Lluvia Intensa");
                        break;
            case "10d": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/lluviasol.png")));
                        Descripcion.setText("Chubascos dispersos");
                        break;
            case "10n": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/lluvialuna.png")));
                        Descripcion.setText("Chubascos dispersos");
                        break;
            case "11d": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tormentasol.png")));
                        Descripcion.setText("Tormenta");
                        break;
            case "11n": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tormentaluna.png")));
                        Descripcion.setText("Tormenta");
                        break;
            case "13d": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nievesol.png")));
                        Descripcion.setText("Nieve");
                        break;
            case "13n": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nieveluna.png")));
                        Descripcion.setText("Nieve");
                        break;
            case "50d": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nieblasol.png")));
                        Descripcion.setText("Niebla");
                        break;
            case "50n": Tiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nieblaluna.png")));
                        Descripcion.setText("Niebla");
                        break;
        }
        
    }

    public void setMaxima(String m) {
        this.Maxima.setText(m);
    }

    public void setMinima(String m) {
        this.Minima.setText(m);
    }

    public void setTemperatura(String t) {
        this.Temperatura.setText(t);
    }

    public void setViento(String v) {
        this.Viento.setText(v);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amanecer;
    private javax.swing.JLabel Atardecer;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Humedad;
    private javax.swing.JLabel Maxima;
    private javax.swing.JLabel Minima;
    private javax.swing.JLabel Temperatura;
    private javax.swing.JLabel Temperatura1;
    private javax.swing.JLabel Tiempo;
    private javax.swing.JLabel Viento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
