/**
 *
 * @author jotaele
 */
package GUI;


public class TiempoDiasPanel extends javax.swing.JPanel {

    /**
     * Creates new form TiempoDiasPanel
     */
    public TiempoDiasPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Icono4 = new javax.swing.JLabel();
        Fecha4 = new javax.swing.JLabel();
        Minima4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Maxima4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Icono3 = new javax.swing.JLabel();
        Fecha3 = new javax.swing.JLabel();
        Minima3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Maxima3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Maxima1 = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JLabel();
        Minima1 = new javax.swing.JLabel();
        Icono1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Icono2 = new javax.swing.JLabel();
        Fecha2 = new javax.swing.JLabel();
        Minima2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Maxima2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(230, 230, 230));
        jPanel3.setLayout(null);

        Icono4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nubesol.png"))); // NOI18N
        jPanel3.add(Icono4);
        Icono4.setBounds(10, 0, 69, 100);

        Fecha4.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        Fecha4.setForeground(new java.awt.Color(111, 111, 111));
        Fecha4.setText("11-10-2016");
        jPanel3.add(Fecha4);
        Fecha4.setBounds(90, 20, 60, 20);

        Minima4.setFont(new java.awt.Font("Ubuntu Light", 1, 15)); // NOI18N
        Minima4.setForeground(new java.awt.Color(0, 66, 255));
        Minima4.setText("20.0");
        jPanel3.add(Minima4);
        Minima4.setBounds(90, 40, 50, 20);

        jLabel7.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 66, 255));
        jLabel7.setText("ºC");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(130, 40, 30, 20);

        Maxima4.setFont(new java.awt.Font("Ubuntu Light", 1, 15)); // NOI18N
        Maxima4.setForeground(new java.awt.Color(255, 16, 0));
        Maxima4.setText("20.0");
        jPanel3.add(Maxima4);
        Maxima4.setBounds(90, 60, 49, 18);

        jLabel8.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 16, 0));
        jLabel8.setText("ºC");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(130, 60, 30, 20);

        setLayout(null);

        jPanel2.setBackground(new java.awt.Color(230, 230, 230));
        jPanel2.setLayout(null);

        Icono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tormentasol.png"))); // NOI18N
        Icono3.setToolTipText("");
        jPanel2.add(Icono3);
        Icono3.setBounds(40, 10, 70, 80);

        Fecha3.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        Fecha3.setForeground(new java.awt.Color(111, 111, 111));
        Fecha3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fecha3.setText("12-10-2016");
        jPanel2.add(Fecha3);
        Fecha3.setBounds(20, 90, 110, 30);

        Minima3.setFont(new java.awt.Font("Ubuntu Light", 1, 15)); // NOI18N
        Minima3.setForeground(new java.awt.Color(0, 66, 255));
        Minima3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Minima3.setText("20.0");
        jPanel2.add(Minima3);
        Minima3.setBounds(30, 120, 40, 20);

        jLabel5.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 66, 255));
        jLabel5.setText("ºC");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 120, 30, 20);

        Maxima3.setFont(new java.awt.Font("Ubuntu Light", 1, 15)); // NOI18N
        Maxima3.setForeground(new java.awt.Color(255, 16, 0));
        Maxima3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Maxima3.setText("20.0");
        jPanel2.add(Maxima3);
        Maxima3.setBounds(30, 140, 40, 18);

        jLabel6.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 16, 0));
        jLabel6.setText("ºC");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(90, 140, 30, 20);

        add(jPanel2);
        jPanel2.setBounds(340, 0, 150, 190);

        jPanel1.setBackground(new java.awt.Color(230, 230, 230));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 16, 0));
        jLabel2.setText("ºC");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 140, 30, 20);

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 66, 255));
        jLabel1.setText("ºC");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 120, 30, 20);

        Maxima1.setFont(new java.awt.Font("Ubuntu Light", 1, 15)); // NOI18N
        Maxima1.setForeground(new java.awt.Color(255, 16, 0));
        Maxima1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Maxima1.setText("20.0");
        jPanel1.add(Maxima1);
        Maxima1.setBounds(20, 140, 50, 18);

        Fecha1.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        Fecha1.setForeground(new java.awt.Color(111, 111, 111));
        Fecha1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fecha1.setText("10-10-2016");
        jPanel1.add(Fecha1);
        Fecha1.setBounds(20, 90, 110, 30);

        Minima1.setFont(new java.awt.Font("Ubuntu Light", 1, 15)); // NOI18N
        Minima1.setForeground(new java.awt.Color(0, 66, 255));
        Minima1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Minima1.setText("20.0");
        jPanel1.add(Minima1);
        Minima1.setBounds(20, 120, 50, 20);

        Icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nievesol.png"))); // NOI18N
        jPanel1.add(Icono1);
        Icono1.setBounds(40, 10, 70, 80);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 150, 190);

        jPanel4.setBackground(new java.awt.Color(230, 230, 230));
        jPanel4.setLayout(null);

        Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nubesol.png"))); // NOI18N
        jPanel4.add(Icono2);
        Icono2.setBounds(40, 10, 70, 80);

        Fecha2.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        Fecha2.setForeground(new java.awt.Color(111, 111, 111));
        Fecha2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fecha2.setText("11-10-2016");
        jPanel4.add(Fecha2);
        Fecha2.setBounds(20, 90, 110, 30);

        Minima2.setFont(new java.awt.Font("Ubuntu Light", 1, 15)); // NOI18N
        Minima2.setForeground(new java.awt.Color(0, 66, 255));
        Minima2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Minima2.setText("20.0");
        jPanel4.add(Minima2);
        Minima2.setBounds(30, 120, 40, 20);

        jLabel9.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 66, 255));
        jLabel9.setText("ºC");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(90, 120, 30, 20);

        Maxima2.setFont(new java.awt.Font("Ubuntu Light", 1, 15)); // NOI18N
        Maxima2.setForeground(new java.awt.Color(255, 16, 0));
        Maxima2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Maxima2.setText("20.0");
        jPanel4.add(Maxima2);
        Maxima2.setBounds(30, 140, 40, 18);

        jLabel10.setFont(new java.awt.Font("Ubuntu Light", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 16, 0));
        jLabel10.setText("ºC");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(90, 140, 30, 20);

        add(jPanel4);
        jPanel4.setBounds(170, 0, 150, 190);
    }// </editor-fold>//GEN-END:initComponents

    public void setFecha1(String F1) {
        this.Fecha1.setText(F1);
    }

    public void setFecha2(String F2) {
        this.Fecha2.setText(F2);
    }

    public void setFecha3(String F3) {
        this.Fecha3.setText(F3);
    }

    public void setTiempo1(String i) {
        
        switch(i) {
            case "01d": Icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/sol.png")));
                        break;
            case "02d": Icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nubesol.png")));
                        break;
            case "03d": Icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nubes.png")));
                        break;
            case "04d": Icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/cubierto.png")));
                        break;
            case "09d": Icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/lluvia.png")));
                        break;
            case "10d": Icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/lluviasol.png")));
                        break;
            case "11d": Icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tormentasol.png")));
                        break;
            case "13d": Icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nievesol.png")));
                        break;
            case "50d": Icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nieblasol.png")));
                        break;
        }
    }
        
    public void setTiempo2(String i) {
        
        switch(i) {
            case "01d": Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/sol.png")));
                        break;
            case "02d": Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nubesol.png")));
                        break;
            case "03d": Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nubes.png")));
                        break;
            case "04d": Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/cubierto.png")));
                        break;
            case "09d": Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/lluvia.png")));
                        break;
            case "10d": Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/lluviasol.png")));
                        break;
            case "11d": Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tormentasol.png")));
                        break;
            case "13d": Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nievesol.png")));
                        break;
            case "50d": Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nieblasol.png")));
                        break;
        }
    }
        
    public void setTiempo3(String i) {
        
        switch(i) {
            case "01d": Icono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/sol.png")));
                        break;
            case "02d": Icono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nubesol.png")));
                        break;
            case "03d": Icono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nubes.png")));
                        break;
            case "04d": Icono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/cubierto.png")));
                        break;
            case "09d": Icono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/lluvia.png")));
                        break;
            case "10d": Icono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/lluviasol.png")));
                        break;
            case "11d": Icono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tormentasol.png")));
                        break;
            case "13d": Icono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nievesol.png")));
                        break;
            case "50d": Icono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/nieblasol.png")));
                        break;
        }
    }
        
    public void setMaxima1(String M1) {
        this.Maxima1.setText(M1);
    }

    public void setMaxima2(String M2) {
        this.Maxima2.setText(M2);
    }

    public void setMaxima3(String M3) {
        this.Maxima3.setText(M3);
    }

    public void setMinima1(String m1) {
        this.Minima1.setText(m1);
    }

    public void setMinima2(String m2) {
        this.Minima2.setText(m2);
    }

    public void setMinima3(String m3) {
        this.Minima3.setText(m3);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fecha1;
    private javax.swing.JLabel Fecha2;
    private javax.swing.JLabel Fecha3;
    private javax.swing.JLabel Fecha4;
    private javax.swing.JLabel Icono1;
    private javax.swing.JLabel Icono2;
    private javax.swing.JLabel Icono3;
    private javax.swing.JLabel Icono4;
    private javax.swing.JLabel Maxima1;
    private javax.swing.JLabel Maxima2;
    private javax.swing.JLabel Maxima3;
    private javax.swing.JLabel Maxima4;
    private javax.swing.JLabel Minima1;
    private javax.swing.JLabel Minima2;
    private javax.swing.JLabel Minima3;
    private javax.swing.JLabel Minima4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
